// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKboZ8I4_eiRaaOxBjBgujy4HqwqWAlrs',
    appId: '1:627931014558:web:45eb35ea81fcc93b0ba28f',
    messagingSenderId: '627931014558',
    projectId: 'insightacademia-747dc',
    authDomain: 'insightacademia-747dc.firebaseapp.com',
    storageBucket: 'insightacademia-747dc.appspot.com',
    measurementId: 'G-6W4K7QG44B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXLBHe4gX0tYzELexvHA_hzXwEOoI1JYY',
    appId: '1:627931014558:android:fce72870a509d72d0ba28f',
    messagingSenderId: '627931014558',
    projectId: 'insightacademia-747dc',
    storageBucket: 'insightacademia-747dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4iA7pDxOzqKeBRX8yX0LOddDTF3tabu4',
    appId: '1:627931014558:ios:0448ecbbc17629180ba28f',
    messagingSenderId: '627931014558',
    projectId: 'insightacademia-747dc',
    storageBucket: 'insightacademia-747dc.appspot.com',
    iosBundleId: 'com.example.majorproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4iA7pDxOzqKeBRX8yX0LOddDTF3tabu4',
    appId: '1:627931014558:ios:3d8254de62da43e80ba28f',
    messagingSenderId: '627931014558',
    projectId: 'insightacademia-747dc',
    storageBucket: 'insightacademia-747dc.appspot.com',
    iosBundleId: 'com.example.majorproject.RunnerTests',
  );
}
